# @package _group_

_target_: mbrl.planning.CEMOptimizer
num_iterations: ${overrides.cem_num_iters}
elite_ratio: ${overrides.cem_elite_ratio}
population_size: ${overrides.cem_population_size}
alpha: ${overrides.cem_alpha}
lower_bound: ???
upper_bound: ???
return_mean_elites: true
device: ${device}
clipped_normal: ${overrides.cem_clipped_normal}
