# @package _group_
name: "pets"

agent:
  _target_: mbrl.planning.TrajectoryOptimizerAgent
  action_lb: ???
  action_ub: ???
  planning_horizon: ${overrides.planning_horizon}
  optimizer_cfg: ${action_optimizer}
  replan_freq: 1
  verbose: ${debug_mode}

normalize: true
normalize_double_precision: true
target_is_delta: true
initial_exploration_steps: ${overrides.trial_length}
freq_train_model: ${overrides.freq_train_model}
learned_rewards: ${overrides.learned_rewards}

num_particles: 20
